[package]
name = "ed448-goldilocks"
version = "0.9.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/crate-crypto/Ed448-Goldilocks"
homepage = "https://github.com/crate-crypto/Ed448-Goldilocks"
documentation = "https://github.com/crate-crypto/Ed448-Goldilocks"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "decaf", "ed448", "ed448-goldilocks"]
description = "A pure-Rust implementation of Ed448 and Curve448 and Decaf"
exclude = [".gitignore", ".github/*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elliptic-curve = { version = "0.13", features = ["hash2curve"] }
subtle = "2.5"
rand_core = "0.6"
serde = { version = "1.0", optional = true }
sha3 = "0.10"

[dependencies.zeroize]
version = "1"
default-features = false
features = ["zeroize_derive"]
optional = true

[features]
default = ["dep:zeroize", "dep:serde"]

[dev-dependencies]
hex-literal = "0.4"
hex = "0.4"
